### ISSUE TITLE
Choose central metrics and monitoring solution

### ISSUE THREAD

**Issue by jde** [coralproject/reef#10]
Challenge: we need to know how people are using our products and how well our products are performing (on an opt in basis.)

Evaluate the two leading candidates for monitoring and metrics:

prometheus.io
elk stack

**Comment by edefikh** [comment]
For current needs we are utilizing free tier of Loggly for Log management of Docker instance logs for xenia/cay/atoll/pillar for demo setup. We also use NewRelic free tier hosted monitoring solution with Mongo plugin and ability to use many open source plugins as we need them.

**Comment by edefikh** [comment]
we are using Loggly for logs monitoring and NewRelic for instance / application monitoring and site24x7 for synthetic transaction monitoring.
