### ISSUE TITLE
What kinds of Configuration should we provide?

### ISSUE THREAD

**Issue by jde** [coralproject/reef#16]
It's a big question.  Let's discuss here and track the ideas we come up with here:

https://github.com/coralproject/reef/wiki/Community-Configuration

**Comment by pablocubico** [comment]
Just posting these ones I came up with for the playground for reference. Some descriptions are in Star Wars Ipsum, but most are self-explanatory.

![config](https://cloud.githubusercontent.com/assets/340766/12064591/922132e2-afa5-11e5-887b-66fa7415e1c9.jpg)

**Comment by gabelula** [comment]
Issue moved to [coralproject/cay #214](https://github.com/coralproject/cay/issues/214) via [**ZenHub.io**](https://www.zenhub.io/)
