### ISSUE TITLE
Design welcome screen for beta application

### ISSUE THREAD

**Issue by jde** [coralproject/reef#21]
Our Trust beta demo release will require login.  The login screen is our best opportunity to provide some welcoming text, messaging and expectation setting.

**Comment by jde** [comment]
A few thoughts on what could go here:

* A very warm and welcoming graphic/text message
* Who to reach out to in order to request an invite
* A note saying that this product is still in the early stages of beta, which means things may go wrong, but, more importantly, we're looking for your input to improve it.
* Feedback instructions (we can also put this on every page of the demo)
  * Email here if you have problems / suggestions
  * Join the conversation here
* A giant thanks!

And of course the login box floating friendly-like to the side.

**Comment by gabelula** [comment]
Moving it to Design Repo. Issue https://github.com/coralproject/design/issues/9
