### ISSUE TITLE
All Beta server requests must be made via https

### ISSUE THREAD

**Issue by jde** [coralproject/reef#22]
In order for our frontend to be able to see our services, we need to be able to hit them using https. 

For example:

```
https://coraldemo.coralproject.net:4000/1.0/query
https://coraldemo.coralproject.net:8080/api/comment
```

Currently, it seems that our server only accepts http requests.  When receiving any https request to ports 4000 (xenia) or 8080 (pillar), we get this error:

```
SSL connection error

ERR_SSL_PROTOCOL_ERROR
Hide details
Unable to make a secure connection to the server. This may be a problem with the server, or it may be requiring a client authentication certificate that you don't have.
```

Ultimately, this goes along with our general policy that all requests must be encrypted.

**Comment by gabelula** [comment]
We have SSL by default.

**Comment by edefikh** [comment]
SSL has been enabled on demo and stage using Nginx reverse proxy setup.
