### ISSUE TITLE
Create coral-anvil.yaml docker-compose install file

### ISSUE THREAD

**Issue by jde** [coralproject/reef#23]
Anvil-connect is an open-source, full featured auth server.  We would like to package it with Coral for clients who do not have their own auth solution.

Create a coral-anvil.yaml docker file that includes all coral applications and anvil-connect.

http://anvil.io

**Comment by jde** [comment]
@edefikh Please update this ticket with the anvil.io progress.

Thanks!

**Comment by edefikh** [comment]
We are currently working with Bill on implementing anvil.io setup. I do not have the progress status yet, but will follow up this week. 

For Cay we are looking into implementing Oauth  using anvil.io 

for Pillar we are still researching best use of Oauth.

**Comment by edefikh** [comment]
anvil.io has been successfully implemented for Xenia, we are documenting the setup process and use case scenarios.

**Comment by edefikh** [comment]
we need documentation for how to use anvil within coral environment

**Comment by aiboyles** [comment]
Based on conversation, Anvil isn't currently being used in Coral. This should be revisited when it is being used and integrated into Coral.

**Comment by kgardnr** [comment]
Closing and will address with auth requirements.
