### ISSUE TITLE
How to start guide

### ISSUE THREAD

**Issue by gabelula** [coralproject/reef#26]
Write a guide on how people can start with the coral system. This is a guide specific for the hackathon for people to quickly start working with our code. 

Goals:

- Understand how all the pieces get together
- Understand how the main app works
- Start to understand the data we are working on and the stats we are getting from it.

**Comment by trenkert** [comment]
any progress on this yet?

**Comment by gabelula** [comment]
We are working on this right now. I moved this issue into the docs repository as we will use that one for documentation.  https://github.com/coralproject/docs/issues/4
