### ISSUE TITLE
Implement notify and restart solution

### ISSUE THREAD

**Issue by jde** [coralproject/reef#28]
We have monitoring for our outwardly facing applications, but internal systems can still go down silently.  When they do they require a manual restart.

Upon failure, all of our services should:
- notify us via push media (sms, email, etc...)
- automatically restart

For bonus points, the most recent slice of log should be delivered.

**Comment by edefikh** [comment]
I have implemented the following solution for monitoring

- Site24x7 to monitor websites , server uptime, performance data, docker stats
- statsd container in staging to gather stats from Pillar
- monit to restart dead processes on mongo and xenia and pillar servers
