### ISSUE TITLE
Document Production ready Ask install

### ISSUE THREAD

**Issue by jde** [coralproject/reef#31]
The Ask product has four components:

* Cay
* Pillar
* Elkhorn
* S3 

Create and document a "production ready" docker compose flow:

* Document the creation of an S3 bucket to store static assets, including making it publicly available 
* Provide documentation, tooling to set up the proper environment variables
* Document process of running the docker compose
* Document accessing Ask in a browser

**Comment by aiboyles** [comment]
This has been updated with two different paths for Ask installation: one, a very basic setup that requires no configuration on the part of the user, and the other allows for adjusting of environment variables, etc.
